### ISSUE TITLE
Use Case #3: Register new user

### ISSUE THREAD

**Issue by takedakento** [CSC207-2022F-UofT/course-project-exam-centre#3]
### Scenario Walkthrough
Person has three options on the start-up screen buttons for “Log In”, “Register new
User” and “Reset Password”. If the user presses “Register new User” they will be met
with a popup that prompts them for an email, a password and a repeated password.
Once they enter in the email and passwords the program checks the application’s
database with all users for a User with the same email and password. This is done
through an interface URegisterDsGateway which would have a method of checking if
the user already exists checkIfAccountExists. The email and password arguments would
be stored within a data structure URegisterDsRequest() which would be done through a
method in URegisterDsGateway called saveUserInfo. Three outcomes:
1. Passwords do not match
a. Asks user to retype the passwords
2. Non-valid email
a. Asks user to enter a valid email

3. User does not exist
a. Program creates a User that stores the email and password
i. registerUser in UserRegisterController is called which creates
URegisterRequestModel containing the email, first name, last
name, password, repeated password and courses using the
URegisterInputBoundary interface which is implemented by
UserRegisterInteractor. The interactor would then call create from
the UserFactory interface which would create an instance of User. If
this were to return True, the UserRegisterInteractor would update
the URegisterResponseModel which would call
prepareSuccessView which is in the URegisterPresenter interface
which would tell the user that their account has been created and
render the home view. If false, prepareFailureView would be called
and tell the user that their account has failed to create.

b. A popup is brought up containing a list of courses that the user is able to
choose or skip
i. If user chooses courses, User is added to the list of users in Course
1. updateCourseMembership would be called by
UpdateCourseMembership which implements
UpdateCMemInputBoundary which would create an
UpdateCMemDsRequestModel which would contain the
userid as well as the courseList that the user has chosen.
updateCourseMembers in the UpdateCMemDsGateway
would then be called and update each Course in the
courseList and adding the userId into the courseList of that
course. If returned True, the UpdateCResponseModel will
update and prepareSuccessView which will notify the user
that they have joined the courses successfully and take them
to the home page. If false, it would notify the user it has
failed and the view will not change.

4. User exists
a. Asks user to Sign In
i. If yes, taken to sign in page
ii. If no, returned to Sign up page

### CRC Model

<img width="626" alt="Screen Shot 2022-10-30 at 3 09 39 PM" src="https://user-images.githubusercontent.com/40901982/198897034-d9cdfbe5-170e-4b3c-a812-130e4037f4a0.png">

**Comment by nykoadionisio** [comment]
Use Case 3 Register New User is in main.
